#!/bin/bash

cmake -S ./ -B build/Release -DCMAKE_BUILD_TYPE=Release
cmake --build build/Release && time ./build/Release/FullDuplexPipe
# perf record -g ./build/Release/FullDuplexPipe
# valgrind --tool=callgrind --trace-children=yes ./build/Release/FullDuplexPipe

# cmake -S ./ -B build/Debug -DCMAKE_BUILD_TYPE=Debug
# cmake --build build/Debug && ./build/Debug/FullDuplexPipe
